# Generated by Django 3.0.8 on 2020-09-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200912_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='amount_raised',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.CharField(default='Australia', max_length=80),
        ),
    ]
