# Generated by Django 3.0.8 on 2020-09-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200926_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='total_raised',
            field=models.IntegerField(default=0),
        ),
    ]
